app/background_processes/application_utils.py
fix: removed logging entries for Database interactions
=> 118 do not log database data

app/utils/applications.py
previous contracts now are ordered by contract start date
=> 132 order past contracts by contract start date

app/utils/applications.py
-changed regex to accept - and _ after @  when validating email
=> 115 new email address is not being saved

.readthedocs.yaml, README.md, app/routers/applications.py, app/routers/awards.py, app/routers/borrowers.py, app/routers/lenders.py, app/routers/security.py, app/routers/statistics.py, app/routers/users.py, docs/Makefile, docs/applications.rst, docs/awards.rst, docs/borrowers.rst, docs/conf.py, docs/index.rst, docs/lenders.rst, docs/requirements.txt, docs/security.rst, docs/statistics.rst, docs/users.rst, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt, setup.py
feat: initial sphynx config and create_lender documentation as example
=> Initial sphynx config

app/background_processes/application_utils.py, app/background_processes/awards_utils.py, app/background_processes/background_utils.py, app/background_processes/colombia_data_access.py, app/background_processes/fetcher.py, app/background_processes/lapsed_applications.py, app/background_processes/message_utils.py, app/background_processes/remove_data.py, app/background_processes/send_reminder.py, app/background_processes/statistics_utils.py, app/background_processes/update_statistic.py, app/db/session.py, app/exceptions.py, app/routers/users.py
Easier to review without whitespace changes: https://github.com/open-contracting/credere-backend/pull/180/files?w=1
=> chore: Tidy exception handling

app/background_processes/colombia_data_access.py
=> closes #192

app/routers/users.py
=> fix: login-mfa: handle all cases

app/routers/users.py, tests/protected_routes/users_test.py, tests/test_users.py
To be deployed with https://github.com/open-contracting/credere-frontend/commit/9946cde8c91bbc27730bbbc811e25e30cc1994bc
=> fix: remove dead code /login and rename /login-mfa to /login

app/commands.py
=> fix: set removed source data to {} instead of ""

app/commands.py, app/mail.py, app/sources/__init__.py, app/sources/colombia.py, app/utils/background.py
=> Bugfix remove data

app/routers/applications.py
=> fix: check for None key before very data field

app/sources/colombia.py, tests/test_applications.py, tests/test_fetcher.py
=> fix: sources: colombia: escape suppliers names

app/mail.py, app/settings.py
ref https://github.com/open-contracting/credere-frontend/issues/76
=> feat: add fathom UTM parameters for email links tracking

app/models.py, app/routers/guest/applications.py, app/routers/lenders.py, app/sources/colombia.py, migrations/versions/63f2125bb242_credit_product_procurement_category.py
=> feat: add new credit product field procurement_method_Category_to_exclude

app/mail.py, app/models.py, email_templates/Application_approved_es.html, migrations/versions/1d633984e7c1_lender_default_message.py
=> feat: add default_pre_approval_message to lender

app/sources/colombia.py
=> fix: Don't set contractperiod_startdate and contractperiod_enddate to tuples

app/routers/applications.py, app/routers/users.py, app/util.py, tests/test_users.py
=> fix: Fix N+1 query in /applications/admin-list

app/sources/colombia.py, app/utils/tables.py
=> chore: Restore quote_plus, after fixing code order

app/routers/applications.py, app/routers/guest/applications.py
=> fix: do not run update_statistics in background

app/commands.py, app/sources/colombia.py
=> chore: Change timedelta(seconds=1) with >= to no timedelta with >, for easier reasoning

app/models.py
=> fix: use default_factory=dict instead of default={}

app/db.py, app/routers/applications.py, app/routers/downloads.py, app/routers/guest/applications.py, app/routers/guest/emails.py, tests/protected_routes/applications_test.py
=> chore: Replace transaction_session with rollback_on_error

app/commands.py
Made a PR since a bug in this logic would delete borrower info 😅
=> perf: Use x.exists() instead of len(x..all()) == 0

app/commands.py, app/utils/statistics.py, docs/contributing/index.rst
fixes #331 e41c54e
fixes #334 91063d8
fixes #335 c4239a0
fixes #336 3128206
fixes #337 e1f9ed8
fixes #338 437e8c3
fixes #339 1cc4542
Values changed in output:
* accepted_count_by_gender (gone in recent commit) and sector_statistics, due to #338
* msme_accepted_count_woman, msme_submitted_count_woman, due to #336
=> Refactor: statistics

app/commands.py, app/mail.py, app/parsers.py, app/routers/applications.py, app/routers/guest/applications.py, app/routers/statistics.py, app/utils/tables.py, docs/contributing/index.rst, tests/test_applications.py, tests/test_lenders.py, tests/test_statistic.py, tests/test_users.py
Regular expressions to find occurrences, ignoring most false positives.
```
(?<![a-z"'])(?<!UserType\.)(?<!\bCONTRACT_UPLOAD_CONFIRMATION_TO_)(?<!\bNEW_APPLICATION_)FI(?!"|le|eld|TNESS|n|cas|rst|lter|rma|duciario|xture|_(COMPLETE_APPLICATION|DOWNLOAD_APPLICATION|DOWNLOAD_DOCUMENT|MESSAGE|REQUEST_INFORMATION|START_APPLICATION)\b)
```
```
(?<!"M)(?<!email-)(?<!\bis_m)(?<!Type\.M)sme(?!s?"|thod)
```
=> chore: Apply style guide for borrower/lender not MSME/FI

app/mail.py
=> fix: add reply to to send_templated_email

app/mail.py, app/models.py, app/settings.py, docs/aws/cloudwatch.rst, docs/frontend.rst
=> 350 pending submit reminder

app/models.py, app/parsers.py, app/routers/guest/applications.py, app/utils/tables.py, migrations/versions/20e0ff589a61_borrower_annual_revenue_field.py, tests/fixtures/borrower_result.json
=> 363 borrower annual revenue

app/commands.py, app/db.py, app/exceptions.py, app/models.py, app/routers/applications.py, app/routers/guest/applications.py, app/routers/guest/emails.py, app/routers/lenders.py, app/routers/users.py, app/settings.py, app/util.py, docs/api/exceptions.rst, docs/api/index.rst, docs/api/util.rst, docs/contributing/sqlalchemy.rst, tests/__init__.py, tests/commands/test_fetch_awards.py, tests/conftest.py
autoflush=False was set in 5ca0f76 (for no reason)
=> Use autoflush and expire_on_commit

app/__main__.py, app/mail.py, app/models.py, app/routers/guest/applications.py, migrations/versions/1fa1da5eb109_user_notification_preferences.py, tests/commands/test_commands.py
=> feat: add notification_preferences per user

app/settings.py, app/util.py, locale/es/LC_MESSAGES/messages.po, tests/routers/test_applications.py
=> 401 new document format

.github/workflows/i18n.yml, locale/es/LC_MESSAGES/messages.po, requirements_dev.in, requirements_dev.txt
- **chore: Remove pre-commit**
- **i18n: Fix workflow and regenerate messages.po**
=> i18n: Fix workflow and regenerate messages.po

email_templates/borrower_invitation.es.html
ref #375 
The rest of the emails will be updated as part of #427
=> feat: improve intro email design

app/models.py
=> fix: use simpler borrower_submitted_at logic for lapsed applications
